class Autogenerated {
  String? type;
  String? id;
  Data? data;
  int? timestampUTC;

  Autogenerated({this.type, this.id, this.data, this.timestampUTC});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    type = json['type'];
    id = json['id'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
    timestampUTC = json['timestampUTC'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['type'] = this.type;
    data['id'] = this.id;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    data['timestampUTC'] = this.timestampUTC;
    return data;
  }
}

class Data {
  String? symbol;
  double? high;
  double? low;
  double? openPrice;
  double? closePrice;
  double? dailyChange;
  double? bid;
  double? ask;
  int? spread;
  int? volume;

  Data(
      {this.symbol,
        this.high,
        this.low,
        this.openPrice,
        this.closePrice,
        this.dailyChange,
        this.bid,
        this.ask,
        this.spread,
        this.volume});

  Data.fromJson(Map<String, dynamic> json) {
    symbol = json['symbol'];
    high = json['high'];
    low = json['low'];
    openPrice = json['openPrice'];
    closePrice = json['closePrice'];
    dailyChange = json['dailyChange'];
    bid = json['bid'];
    ask = json['ask'];
    spread = json['spread'];
    volume = json['volume'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['symbol'] = this.symbol;
    data['high'] = this.high;
    data['low'] = this.low;
    data['openPrice'] = this.openPrice;
    data['closePrice'] = this.closePrice;
    data['dailyChange'] = this.dailyChange;
    data['bid'] = this.bid;
    data['ask'] = this.ask;
    data['spread'] = this.spread;
    data['volume'] = this.volume;
    return data;
  }
}